language: cpp

env:
  global:
    - ARDUINO_PACKAGE_VERSION=1.8.2
    - DISPLAY=:1.0

  matrix:
    - BOARD=uno SKETCH=examples/DCF77_Scope/DCF77_Scope.ino
    - BOARD=uno SKETCH=examples/MB_Emulator/MB_Emulator.ino
    - BOARD=uno SKETCH=examples/Simple_Clock/Simple_Clock.ino
    - BOARD=uno SKETCH=examples/Simple_Clock_with_Timezone_Support/Simple_Clock_with_Timezone_Support.ino
    - BOARD=uno SKETCH=examples/Superfilter/Superfilter.ino
    - BOARD=uno SKETCH=examples/Swiss_Army_Debug_Helper/Swiss_Army_Debug_Helper.ino
    - BOARD=uno SKETCH=examples/The_Clock/The_Clock.ino
    - BOARD=uno SKETCH=examples/Time_Switch/Time_Switch.ino
    - BOARD=uno SKETCH=examples/Unit_Test/Unit_Test.ino

    - BOARD=diecimila:cpu=atmega168 SKETCH=examples/DCF77_Scope/DCF77_Scope.ino
    - BOARD=diecimila:cpu=atmega168 SKETCH=examples/MB_Emulator/MB_Emulator.ino
    - BOARD=diecimila:cpu=atmega168 SKETCH=examples/Simple_Clock/Simple_Clock.ino
    - BOARD=diecimila:cpu=atmega168 SKETCH=examples/Simple_Clock_with_Timezone_Support/Simple_Clock_with_Timezone_Support.ino
    - BOARD=diecimila:cpu=atmega168 SKETCH=examples/Superfilter/Superfilter.ino
    - BOARD=diecimila:cpu=atmega168 SKETCH=examples/Swiss_Army_Debug_Helper/Swiss_Army_Debug_Helper.ino
    - BOARD=diecimila:cpu=atmega168 SKETCH=examples/The_Clock/The_Clock.ino
    - BOARD=diecimila:cpu=atmega168 SKETCH=examples/Time_Switch/Time_Switch.ino
    - BOARD=diecimila:cpu=atmega168 SKETCH=examples/Unit_Test/Unit_Test.ino

matrix:
  allow_failures:
    - env: BOARD=uno SKETCH=examples/Unit_Test/Unit_Test.ino
    - env: BOARD=diecimila:cpu=atmega168 SKETCH=examples/Unit_Test/Unit_Test.ino

before_script:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/xvfb_$TRAVIS_JOB_NUMBER.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
  - wget -q -O- http://downloads.arduino.cc/arduino-$ARDUINO_PACKAGE_VERSION-linux64.tar.xz | unxz -c | tar -xf -
  - mkdir -p ~/Arduino/libraries/
  - ln -s $TRAVIS_BUILD_DIR ~/Arduino/libraries/

script:
  - $TRAVIS_BUILD_DIR/arduino-$ARDUINO_PACKAGE_VERSION/arduino --verbose --verify --board arduino:avr:$BOARD $TRAVIS_BUILD_DIR/$SKETCH
